/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_polkadot_sr25519_SR25519 */

#ifndef _Included_org_polkadot_sr25519_SR25519
#define _Included_org_polkadot_sr25519_SR25519
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_polkadot_sr25519_SR25519
 * Method:    test1
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_org_polkadot_sr25519_SR25519_test1
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_polkadot_sr25519_SR25519
 * Method:    sr25519_derive_keypair_hard
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_org_polkadot_sr25519_SR25519_sr25519_1derive_1keypair_1hard
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_polkadot_sr25519_SR25519
 * Method:    sr25519_derive_keypair_soft
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_org_polkadot_sr25519_SR25519_sr25519_1derive_1keypair_1soft
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_polkadot_sr25519_SR25519
 * Method:    sr25519_derive_public_soft
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_org_polkadot_sr25519_SR25519_sr25519_1derive_1public_1soft
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_polkadot_sr25519_SR25519
 * Method:    sr25519_keypair_from_seed
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_org_polkadot_sr25519_SR25519_sr25519_1keypair_1from_1seed
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_polkadot_sr25519_SR25519
 * Method:    sr25519_sign
 * Signature: ([B[B[B[BI)V
 */
JNIEXPORT void JNICALL Java_org_polkadot_sr25519_SR25519_sr25519_1sign
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     org_polkadot_sr25519_SR25519
 * Method:    sr25519_verify
 * Signature: ([B[BI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_polkadot_sr25519_SR25519_sr25519_1verify
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
